config/routes.rb
Rails.application.routes.draw do
  get 'messages/new'
  devise_for :users
  root to: "pages#home"
  get "users/:id", to: "users#show", as: :user

  resources :recipients do
  get "confirmation", to: "donations#confirmation", as: :confirmation
    resources :donations, only: %i[new create]
  end
  # get "confirmation", to: "donations#confirmation", as: :confirmation

  resources :recipients do
    resources :messages, only: [:new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :user, required: false
  belongs_to :recipient
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :recipient
end

app/models/recipient.rb
class Recipient < ApplicationRecord
  belongs_to :user
  has_many :donations, dependent: :destroy
  has_many :messages, dependent: :destroy
  # has_many :donators, through: :donations, source: :user
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :recipients, dependent: :destroy
  has_many :donations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  skip_before_action :authenticate_user!

  def new
    @recipient = Recipient.find(params[:recipient_id])
    @donation = Donation.new
    # @recipients = Recipient.all
  end

  def create
    @donation = Donation.new(donation_params)
    @recipient = Recipient.find(params[:recipient_id])
    @donation.recipient = @recipient
    @donation.user = current_user
    @donation.save!

    session[:donation] = @donation

    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        price_data: {
          currency: 'gbp',
          unit_amount: @donation.amount*100,
          product_data: {
            name: @recipient.name,
            description: "test"
          },
        },
        quantity: 1,
      }],
      mode: 'payment',
      success_url:  new_recipient_donation_url(@recipient),
      cancel_url: root_url
    )
    @donation.update(checkout_session_id: session.id)

    redirect_to recipient_confirmation_path(@recipient, donation: @donation)
  end

  def confirmation
    # @donation = Recipient.find(params[:recipient_id]).donations.last.amount
    @donation = Donation.find(params[:donation])
    @recipient = Recipient.find(params[:recipient_id])
  end

  private

  def donation_params
    params.require(:donation).permit(:amount, :message, :recipient_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    # We need @restaurant in our `simple_form_for`
    @recipient = Recipient.find(params[:recipient_id])
    @message = Message.new
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home
  end
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  skip_before_action :authenticate_user!, except: [:index]

  def index
    # if someone is logged in
    if current_user.present?
      @user = current_user
      # if the user is an admin
      if current_user.admin?
        # if there are search params
        if params[:query].present?
          @recipients = Recipient.where(user: current_user).where("name ILIKE ?", "%#{params[:query]}%").reverse
        else
          @recipients = Recipient.where(user: current_user)
        end
      else
        all_donations = Donation.where(user: current_user)
        @donations = all_donations.select(:recipient_id).distinct.reverse

        if (session[:donation]).present?
          sign_up = session[:donation]
          add_donation = Donation.find(sign_up['id'])
          add_donation.user = current_user
          add_donation.save
          @donations = all_donations.select(:recipient_id).distinct.reverse
          session.clear
        end

      end
    end
  end

  def show
    @recipient = Recipient.find(params[:id])
    if current_user.present?
      if current_user.admin?
        @donations = Donation.where(recipient: @recipient)
      else
        @donations = Donation.where(user: current_user)
      end
    end
    @donation = Donation.new(recipient: @recipient, user: current_user)
  end

  def new
    @recipient = Recipient.new
  end

  def create
    @recipient = Recipient.new(recipient_params)
    @recipient.user = current_user
    @recipient.save!
    #Previous version linking to the heroku app address
    # https://www.good-deed.co/recipients/#{@recipient.id}
    #qrcode = RQRCode::QRCode.new("https://good-deed1.herokuapp.com/recipients/#{@recipient.id}")
   # www.good-deed.co
    qrcode = RQRCode::QRCode.new("https://good-deed1.herokuapp.com/recipients/#{@recipient.id}")
    png = qrcode.as_png(
      bit_depth: 1,
      border_modules: 1,
      color_mode: ChunkyPNG::COLOR_GRAYSCALE,
      color: "black",
      file: nil,
      fill: "white",
      module_px_size: 10,
      resize_exactly_to: false,
      resize_gte_to: false,
      size: 250
    )

    Cloudinary::Uploader.upload("#{png.to_data_url}",
      :public_id => "qr_code#{@recipient.id}",
      :use_filename => true
      )

    redirect_to recipient_path(@recipient)
  end

  def edit
    @recipient = Recipient.find(params[:id])
  end

  def update
    recipient = Recipient.find(params[:id])
    recipient.update(recipient_params)
    redirect_to recipient_path(recipient)
  end

  def destroy
    @recipient = Recipient.find(params[:id])
    @recipient.destroy
    redirect_to recipients_path, status: :see_other
  end

  private

  def recipient_params
    params.require(:recipient).permit(:name, :bio, :qr_code, :photo)
  end
end

def create_pictures
  photos = params.dig(:recipient, :pictures) || []
  photos.each do |photo|
    @recipient.pictures.create(photo: photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @recipients = Recipient.where(user: @user) if current_user.admin == true
    @donations = Donation.where(user: @user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin?
    if current_user.present?
      current_user.admin?
    end
  end


  def user_name
    if current_user.present?
      current_user.first_name
    else
      'Changemaker'
    end
  end
end

app/views/donations/confirmation.html.erb
<p class= "bold-text"> Please confirm that you want to pay £<%= @donation.amount %> to <%= @recipient.name %></p>

<div class= "btn-centre">
  <button id="pay" class="btn-blue-lrg">Confirm Payment</button>
</div>
 <script src="https://js.stripe.com/v3/"></script>
  <script>
    const paymentButton = document.getElementById('pay');

    paymentButton.addEventListener('click', () => {
      const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
      stripe.redirectToCheckout({
        sessionId: '<%= @donation.checkout_session_id %>'
      });
    });
  </script>

app/views/donations/create.html.erb
<h1> Hello changemarker</h1>

<body>
<p> Enter the amount you would like to donate </p>
<ui>
   <li> Empty text box </li>
     <li> £3 </li>
      <li> £5 </li>
        <li> £7 </li>
  </ui>

<div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault" />
  <label class="form-check-label" for="flexCheckDefault">Default checkbox</label>
</div>


</body>

app/views/donations/new.html.erb
<div class="container">
  <div>
    <h1 class="title-white small text-left">Thank you <%= user_name %> </h1>
  </div>
  <div>
    <p class="p-blue-bigger">You're making the world a better place!</p>
  </div>
    <% if user_signed_in? %>
      <div class="d-flex justify-content-center">
        <%= link_to "My donations", recipients_path, class: "btn-blue-lrg d-flex" %>
      </div>
    <% else %>
      <div class="d-flex justify-content-center">
        <%= link_to "Create Account", new_user_registration_path, class: "btn-blue-lrg d-flex" %>
      </div>
    <% end %>
  <div>
    <p class="italic-bold ml-1">Feel free to share your good deed of the day:</p>
  </div>
  <div class="d-flex justify-content-around">
      <i class="fa-brands fa-facebook-f"></i>
      <i class="fa-brands fa-instagram"></i>
      <i class="fa-brands fa-twitter"></i>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Good Deed</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <%# google fonts added %>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500;600&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans:ital@0;1&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/866e025c03.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
   <div class="wrapper">
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%# realised the footer is only on one page so maybe best to not have one %>
    <%# <%= render "shared/footer" %>
     </div>
    </div>
  </body>
</html>

app/views/messages/new.html.erb
<h1>Messages#new</h1>
<p>Find me in app/views/messages/new.html.erb</p>

app/views/pages/home.html.erb
<div class="container">

<%# ALL WILL SEE THIS, LOGGED IN OR NOT, ADMIN OR USER %>
  <div class="d-flex justify-content-center">
    <%=image_tag "https://res.cloudinary.com/dl9jjyyew/image/upload/v1662643947/GoodDeedWhite_ufm7vi.png", style: 'height:auto;width:90%;', class: "logo-title" %>
  </div>


  <%# if no one is logged in %>
    <% if !user_signed_in? %>
    <%# show the donate button which will open camera %>
      <div class="d-flex justify-content-center">
        <label for="donate" class="btn-orange-lrg">Donate</label>
        <input type="file" name="photo" id="donate">
      </div>
      <div class="container">
      <div class="ap-blue">
        <p>
          Some of the most vulnerable people in society can find themselves homeless. Like those with mental health issues or young people who are victims of abuse...
        </p>

      <div class="d-flex justify-content-center">
        <%# This is for a modal or scroll down %>
        <!-- Button trigger modal -->
        <button type="button" class="btn-blue-sml" data-bs-toggle="modal" data-bs-target="#exampleModal">
          Read More
        </button>
        </div>
      </div>
    </div>

      <%# <div class="wrapper">
        <div class = "container">
          <br>      <br>      <br>      <br>
          <div class="d-flex justify-content-center">
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.
            Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
            when an unknown printer took a galley of type and scrambled it to make a type specimen book.
            It has survived not only five centuries, but also the leap into electronic typesetting,
            remaining essentially unchanged. It was popularised in the 1960s with the release of
            Letraset sheets containing Lorem Ipsum passages, and more recently with
            desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
            </p>
          </div>
        </div>
      </div> %>

        <%# if the user is signed in and not an admin %>
    <% elsif user_signed_in? && !admin? %>
        <%# show a link to my donations so i can see them all %>
        <div class="d-flex justify-content-center">
          <%= link_to "My Donations", recipients_path, class: "btn-blue-sml d-flex" %>
        </div>
        <div class="d-flex justify-content-center">
          <label for="donate" class="btn-orange-lrg">Donate</label>
          <input type="file" name="photo" id="donate">
        </div>
          <div class="container m-3">
            <div class="ap-blue">
          Some of the most vulnerable people in society can find themselves homeless.
          Like those with mental health issues or young people who are victims of abuse...
          </p>
        <div class="d-flex justify-content-center">
          <%# This is for a modal or scroll down %>
          <!-- Button trigger modal -->
          <button type="button" class="btn-blue-sml" data-bs-toggle="modal" data-bs-target="#exampleModal">
            Read More
          </button>
        </div>
      </div>


      <% else %>
      <%# if the user is admin %>
        <div class="d-flex justify-content-center">
          <h1 class="title-blue">Hello <%= current_user.first_name %> </h1>
        </div>
        <div class="d-flex justify-content-center">
        <%# show the link to my people %>
          <%= link_to "My People", recipients_path, class: "btn-blue-lrg d-flex" %>
        </div>
      <% end %>


<%# modal pop up when you click read more %>
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="title-blue" id="exampleModalLabel">Good Deed</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body mx-3">
        <p class ="p-blue">Some of the most vulnerable people in society can find themselves homeless.
        Like those with mental health issues or young people who are victims of abuse.
        </p>
        <p class="p-blue">With your help, good deed work with homeless people to help get them off the street
        into shelters and make sure they have food and drink.
        </p>
        <p class="italic-bold">How does it work?</p>
        <ol>
          <li class="p-blue-sml">Shelters provide people facing homelessness with a prepaid card with a QR code
          which is specific to them.
          </li><br>
          <li class="p-blue-sml">You can scan this QR code from the camera on your phone and it will link you
          to their page displaying their photo and more information about how they ended up
          in this position.
          </li><br>
          <li class="p-blue-sml">Then, you can donate money to their card so they can use if and when they need
          in specific stores like Sainsburys and Tesco or for a night in a local shelter
          </li>
        </ol>
        <p class="italic-bold">Which means...</p>
        <ul>
          <li class="p-blue-sml">No more worrying where the money is going</li><br>
          <li class="p-blue-sml">Much more people getting off the streets and getting their lives on track</li>
        </ul><br>
        <p class="italic-bold">What good deed are you going to do today?</p>
        </div>
      </div>
    </div>
</div>

app/views/recipients/_new_donation.html.erb
<div class ="container" data-controller="amount">
  <hr class="solid">
  <h1 class="title-blue">Hello <%= user_name %> </h1> <br>
  <p class="p-blue"> Enter the amount you would like to donate</p>

  <%= simple_form_for([@recipient, @donation]) do |f| %>
    <%= f.input :message,
                :label => false,
                placeholder: "Leave a message",
                :input_html => { :class => 'form-inputs'} %>
    <%= f.input :amount,
                :label => false,
                placeholder: "Enter amount",
                :input_html => { :class => 'form-inputs'}  %>
    <div class="d-flex justify-content-center">
      <ul>
        <button data-action="click->amount#donate" type="button" class="btn-orange-sml bold-text">£3</button>
        <button data-action="click->amount#donate"type="button" class="btn-orange-sml bold-text">£5</button>
        <button data-action="click->amount#donate" type="button" class="btn-orange-sml bold-text">£7</button>
      </ul>
    </div>
    <div class="form-actions d-flex justify-content-center" id= "new_donation">
      <%= f.button :submit, "Change a life!", class:"btn-blue-sml" %>
    </div>
  <% end %>
  <br>

</div>

app/views/recipients/edit.html.erb
<div class="container">
    <div class="form">
      <h1 class="title-blue">Make changes</h1>
      <br>
      <%= simple_form_for @recipient do |f| %>
      <div class="form-input">
        <%= f.input :name, :label => false, placeholder: "Name", :input_html => { :class => 'form-inputs'}%>
        <%= f.input :bio, :label => false, placeholder: "Share their story", :input_html => { :class => 'form-inputs'}  %>
        <%= f.input :photo, :label => false, placeholder: "Upload a photo", :input_html => { :class => 'form-inputs'} %>
      </div>
      <div class="form-actions">
        <div class="d-flex justify-content-center">
          <%# want this to go to recipient_path but it takes me to recipients.id instead of /id %>
          <%= f.button :submit, "Complete", class: "btn-blue-sml"  %>
        </div>
      </div>
    </div>
    <% end %>
  </div>

app/views/recipients/index.html.erb
<%# title to welcome the admin with their name %>
<div class="d-flex justify-content-center">
  <h1 class="title-white">Hello <%= current_user.first_name %> </h1>
</div>
  <%# if you are an admin you can create a profile and search %>
  <% if admin? %>
    <div class="d-flex justify-content-center">
      <%= link_to "Create a profile", new_recipient_path, class: "btn-blue-sml" %>
    </div>
    <div class="d-flex justify-content-center">
      <%= form_with url: recipients_path, method: :get, class: "search d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        placeholder: "Search for profile 🔍",
        class:'search-form' %>
      <% end %>
    </div>
  <% end %>

  <%# User Actions being represents%>

  <div class="cards d-flex justify-content-center">
    <div class= "row justify-content-between">

        <% if admin? == false %>
          <% if @user.donations.present? %>
            <p class="p-blue">You have donated to...</p>
              <% @donations.each do |donation| %>
                <% recipient = Recipient.find(donation.recipient_id) %>
                <%= link_to recipient_path(recipient) do %>
                  <div class="card">
                    <% if recipient.photo.key.present? %>
                      <%= link_to recipient_path(recipient) do %>
                        <%= cl_image_tag recipient.photo.key, height: 150, width: 150, crop: :fill, class: "image-cropper-index" %>
                        <p class= "p-blue-bigger d-flex justify-content-center names" ><%= recipient.name%></p>
                      <% end %>
                    <% end %>
                  </div>
                <% end %>
              <% end %>
          <% else %>
          <p class= "p-blue-bigger">You have not donated to anyone, yet</p>
            <div class="d-flex justify-content-center">
              <label for="donate" class="btn-orange-lrg">Donate</label>
              <input type="file" name="photo" id="donate">
            </div>
          <% end %>
        <% end %>

<%# <p><%= link_to recipient.name, recipient_path(recipient), class: "p-blue-bigger d-flex justify-content-center" %>

      <% if admin? %>
          <%# <%= link_to 'new recipient', new_recipient_path  %>
          <% @recipients.each do |recipient| %>
            <div class = "card">
              <% if recipient.photo.key.present? %>
                <%= link_to recipient_path(recipient) do %>
                  <%= cl_image_tag recipient.photo.key, height: 150, width: 150, crop: :fill, class:"image-cropper-index" %>
                  <p class="p-blue d-flex justify-content-center names"><%= recipient.name %></p>
                <% end %>
              <% end %>
            </div>
          <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/recipients/new.html.erb
<%# This is /recipients/new %>
<%# I dont want input name / bio and qr code I want this to go inside as a placeholder %>
<div class="container">
    <div class="form">
      <h1 class="title-blue">Create a profile</h1>
      <br>
          <%= simple_form_for @recipient do |f| %>
          <div class="form-input">
            <%= f.input :name, :label => false, placeholder: "Name", :input_html => { :class => 'form-inputs'}%>
              <%= f.input :bio, :label => false, placeholder: "Share their story", :input_html => { :class => 'form-inputs'}  %>
              <%= f.input :photo, :label => false, placeholder: "Upload a photo", :input_html => { :class => 'form-inputs'} %>
            </div>
           <div class="form-actions">
           <div class="d-flex justify-content-center">
           <%# want this to go to recipient_path but it takes me to recipients.id instead of /id %>
      <%= f.button :submit, "Complete", class: "btn-blue-sml"  %>
    </div>
    <% end %>
  </div>

app/views/recipients/show.html.erb
<div class="container">
  <%# go back to previous page (index) %>
  <div class ="link-to justify-content-between d-flex m-3">
    <%= link_to recipients_path do %>
    <i class="fa-solid fa-chevron-left" title="Back"></i>
    <% end %>
  </div>

  <div class="white-background">
    <%# recipient name %>
    <h1 class="title-blue small"> <%= @recipient.name.capitalize %> </h1>
      <%# if the recipient has a photo show their picture %>
    <div class="image-cropper my-3">
      <% if @recipient.photo.key.present?%>
        <%= cl_image_tag @recipient.photo.key, height: 300, width: 400, crop: :fill, class: "prof-img" %>
      <% end %>
    </div>


    <%# admin you can edit and delete%>
    <div class="admin-prof">
      <% if admin?  %>
        <div class="link-to d-flex justify-content-center">
          <%# edit a profile %>
          <%= link_to edit_recipient_path do %>
            <i class="fa-solid fa-pen-to-square" title="Edit"> </i>
          <% end %>
          <%# delete a profile %>
          <%= link_to recipient_path(@recipient), data: { "turbo-method": :delete, "turbo-confirm": "are you sure?"} do %>
            <i class="fa-solid fa-trash" title="Delete"> </i>
          <% end %>
        </div>
      <% end %>
    </div>

    <%# recipient bio %>
    <div class="container ">
      <p class ="p-blue"><%= @recipient.bio %></p>
      <%# if admin show QR code that has been created %>
      <% if admin? %>
        <div class="m-auto">
          <% str = cl_image_path "qr_code#{@recipient.id}.png" %>
          <%# localhost:%>
          <%# <% newPath = str.sub /\/v\d*\/development/, '' %>
          <%# heroku%>
          <% newPath = str.sub /\/v\d*\/production/, '' %>
          <img src="<%= newPath %>" alt="qr-code">
        </div>
      <% end %>
  </div>

  <div class="container">
    <% if admin? %>
    <%# messages from the donations %>
      <hr class="solid">
      <div>
        <p class="italic-bold">Messages</p>
      </div>
      <div>
        <div class="message-product">
          <% @donations.each do |donation| %>
            <hr class="solid">
              <div class="message-product-infos d-flex justify-content-left">
                <h2 class="p-blue-bigger bold">£<%= donation.amount %></h2>
                <p class="p-blue-med"><%= donation.message %></p>
              </div>
              <div class="">
                <p class="p-blue-sml right bold mr-3"><%= donation.created_at.strftime("%d %b") %></p>
              </div>
          <% end %>
      </div>
    <% end %>

  <%#  if user you will be able to donate here%>
  <% if !admin? %>
    <div class="d-flex sflex-column">
      <div class="m-auto">
        <%# show a link to my donations so i can see them all %>
        <%# render "new_donation" %>
        <%= render "new_donation", donation: @donation %>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div>
    <i class="fa-sharp fa-solid fa-house"></i>
  </div>

  <% if user_signed_in? %>
    <% if !admin? %>
      <%= link_to 'my donations', recipients_path, class: "btn btn-flat" %>
    <% end %>

    <% if admin? %>
      <%= link_to 'my recipients', recipients_path, class: "btn btn-flat" %>
    <% end %>
  <% end %>

  <div>
    <i class="fa-regular fa-user"></i>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
<%# create a nav bar with the logo button on left which will take you home %>
  <%= link_to root_path, class: "navbar-brand" do %>
  <%= image_tag "https://res.cloudinary.com/dl9jjyyew/image/upload/v1662643947/GoodDeed_GD_g4wtuh.png"  %>
  <% end %>

<%# if the user is signed in they will see log out %>
  <% if user_signed_in? %>
    <% if admin? %>
      <div class="navbar-item link-to">
        <%# create a profile %>
        <%= link_to new_recipient_path do %>
          <i class="fa-solid fa-user-plus" title="Create a Profile"></i>
          <% end %>
      </div>
    <% end %>
      <div class="navbar-item link-to">
        <%# log out %>
        <%= link_to destroy_user_session_path, data: {turbo_method: :delete} do %>
        <i class="fa-solid fa-right-from-bracket" title="Log Out"></i>
        <% end %>
      </div>
  <% else %>
    <div class="navbar-item link-to">
      <%# login %>
      <%= link_to new_user_session_path do %>
        <i class="fa-solid fa-right-to-bracket" title="Login"></i>
      <% end %>
    </div>
  <% end %>
</div>

<%# if they are an admin they will see a create a profile button which will take them to the create page %>

app/views/users/show.html.erb
<%# THIS WILL BE A PAGE FOR THE USER TO EDIT THEIR PROFILE
THIS IS WRONG AT THE MOMENT %>

<div class="profile-top">
  <h1 class="title-white">Hello <%= current_user.first_name %> </h1>
  <%= image_tag "https://kitt.lewagon.com/placeholder/users/sarahlafer", class: "avatar-bordered my-3", alt: "avatar-bordered" %>
  <% if !admin? %>
    <%= link_to "My donations", "", class: "btn-blue-lrg py-3" %>
  <% end %>
  <h2 class="italic-bold py-3">Kind people are my kinda people</h2>
</div>
<div class="profile-bottom">
  <div class="bottom-top d-flex">
    <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9JISkH2GrxO00DQH4TZSdu0F51TmXijKXuiO2qOY&s", class: "smiley", alt: "avatar-bordered" %>
    <h2 class="italic-bold prof-text">You have made 10 donations! Thank you!</h2>
  </div>
  <div class="bottom-bottom">
  <% if !admin? %>
    <%= link_to "Donate", recipient_path, class: "btn-orange-lrg" %>
  <% end %>
  </div>
</div>